services:
  turso:
    platform: linux/amd64
    container_name: turso
    restart: unless-stopped
    image: "richan/turso-dev:latest"
    environment:
      - TURSO_DB_FILE=/var/lib/turso/turso.sqlite
    ports:
      - "8081:8080"
